import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

// next/core-web-vitals pulls in eslint-plugin-react, eslint-plugin-react-hooks,
// and eslint-plugin-jsx-a11y; next/typescript adds typescript-eslint on top --
// both required by devDependencies below since neither ships with plain `eslint`.
const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is regenerated by Next.js itself and explicitly marked
    // "should not be edited" -- its triple-slash references trip
    // @typescript-eslint/triple-slash-reference, but that's Next's own
    // generated code, not ours to fix.
    ignores: [".next/**", "node_modules/**", "next-env.d.ts"],
  },
];

export default eslintConfig;
