name: mail_justu
services:
  mail_justu_opendkim:
    image: instrumentisto/opendkim
    container_name: mail-opendkim
    restart: unless-stopped
    volumes:
      - opendkim_config:/etc/opendkim
    networks:
      - mail_justu_network

  mail_justu_dkim_sync:
    build: ./dkim-sync
    container_name: mail-dkim-sync
    restart: unless-stopped
    pid: service:mail_justu_opendkim
    env_file:
      - ./.env/api.env
    volumes:
      - opendkim_config:/etc/opendkim
    depends_on:
      mail_justu_opendkim:
        condition: service_started

networks:
  mail_justu_network:
    driver: bridge
volumes:
  opendkim_config:
    name: mail_justu_opendkim_config
