import { useState, useEffect, useRef } from "react";
import {
  X,
  Minus,
  Paperclip,
  Send,
  ChevronDown,
  ChevronRight,
  File as FileIcon,
  Trash2,
  Maximize2,
  Minimize2,
  Bold,
  Italic,
  Underline,
  List,
  ListOrdered,
  Link2,
  PenLine,
} from "lucide-react";
import { getComposeStyle, setComposeStyle } from "../settings";

export interface ComposeDraft {
  to: string;
  cc?: string;
  bcc?: string;
  subject: string;
  body: string;
  // Rich-text mirror of `body` -- generated by the contentEditable editor
  // below (see bodyRef/handleBodyInput). `body` stays the plain-text
  // extraction of the same content so drafts/plain send still work if
  // it's absent (e.g. a draft saved before this existed).
  html?: string;
  from?: string;
  attachments?: File[];
  // Set when this draft was opened from the Drafts folder -- lets saving
  // and sending replace the original message instead of duplicating it.
  draftUid?: number;
  draftFolder?: string;
  // Set when replying/forwarding -- carried through to the outgoing
  // In-Reply-To/References headers so the message threads with its parent.
  inReplyTo?: string;
  references?: string[];
  // Set when replying/forwarding -- the previous message's content, kept
  // out of `body` so it renders as its own read-only block instead of
  // sharing the textarea with what the user is actively typing. Appended
  // back onto `body` at send time (see App.tsx's handleSend).
  quoteHeading?: string;
  quoteBody?: string;
}

export interface ContactSuggestion {
  email: string;
  name: string;
}

interface ComposeModalProps {
  initialDraft: ComposeDraft;
  onClose: () => void;
  onSaveDraft: (draft: ComposeDraft) => void;
  onSend: (draft: ComposeDraft) => void;
  onScheduleSend: (draft: ComposeDraft, sendAt: Date) => void;
  onDeleteDraft?: (draft: ComposeDraft) => void;
  onValidationError: (message: string) => void;
  onEditSignature: () => void;
  primaryEmail: string;
  aliases: string[];
  contacts: ContactSuggestion[];
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.ceil(bytes / 1024)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// A small bottom-right popup (the default desktop "compose style") doesn't
// work on a phone screen -- there's no room for it next to real content, and
// the on-screen keyboard eats whatever little height it had. Every mobile
// mail client (Gmail, Apple Mail, ...) opens compose full-screen instead, so
// force that below the `md` breakpoint regardless of the user's desktop
// popup/full preference (see `full`/`toggleFull` below, still desktop-only).
function useIsMobile() {
  const [isMobile, setIsMobile] = useState(
    () => window.matchMedia("(max-width: 767px)").matches,
  );
  useEffect(() => {
    const mq = window.matchMedia("(max-width: 767px)");
    const handler = () => setIsMobile(mq.matches);
    mq.addEventListener("change", handler);
    return () => mq.removeEventListener("change", handler);
  }, []);
  return isMobile;
}

function ToolbarButton({
  icon: Icon,
  title,
  onRun,
}: {
  icon: React.ComponentType<{ size?: number }>;
  title: string;
  onRun: () => void;
}) {
  return (
    <button
      type="button"
      title={title}
      // mousedown (not click) + preventDefault -- click would fire after
      // the editor has already lost focus/selection to this button, so
      // execCommand would have nothing to apply to.
      onMouseDown={(e) => {
        e.preventDefault();
        onRun();
      }}
      className="rounded p-1.5 transition hover:opacity-80"
      style={{ color: "var(--text-muted)" }}
    >
      <Icon size={14} />
    </button>
  );
}

// Recipient input with a suggestion dropdown drawn from mail seen so far
// this session (see App.tsx's contactsRef) -- not a real address book,
// just autocomplete over people you've already exchanged mail with.
function RecipientField({
  value,
  onChange,
  placeholder,
  contacts,
  borderBottom,
}: {
  value: string;
  onChange: (value: string) => void;
  placeholder: string;
  contacts: ContactSuggestion[];
  borderBottom?: boolean;
}) {
  const [open, setOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    function handleClick(e: MouseEvent) {
      if (
        containerRef.current &&
        !containerRef.current.contains(e.target as Node)
      )
        setOpen(false);
    }
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, [open]);

  // Suggest against whatever's being typed after the last comma, so
  // picking a suggestion for the 2nd+ recipient doesn't need clearing the
  // field first.
  const segments = value.split(",");
  const current = segments[segments.length - 1].trim().toLowerCase();
  const matches =
    current.length > 0
      ? contacts
          .filter(
            (c) =>
              c.email.toLowerCase().includes(current) ||
              c.name.toLowerCase().includes(current),
          )
          .slice(0, 6)
      : [];

  function pick(contact: ContactSuggestion) {
    const prefix = segments.slice(0, -1);
    onChange([...prefix, ` ${contact.email}`].join(",").replace(/^,\s*/, ""));
    setOpen(false);
  }

  return (
    <div className="relative flex-1" ref={containerRef}>
      <input
        value={value}
        onChange={(e) => {
          onChange(e.target.value);
          setOpen(true);
        }}
        onFocus={() => setOpen(true)}
        placeholder={placeholder}
        className={`w-full px-4 py-2.5 text-base outline-none sm:text-sm ${borderBottom ? "border-b" : ""}`}
        style={{
          borderColor: "var(--border)",
          color: "var(--text)",
          background: "transparent",
        }}
      />
      {open && matches.length > 0 && (
        <div
          className="absolute left-0 right-0 top-full z-10 max-h-48 overflow-y-auto rounded-b-lg border shadow-lg"
          style={{
            background: "var(--bg-elevated)",
            borderColor: "var(--border)",
          }}
        >
          {matches.map((c) => (
            <button
              key={c.email}
              type="button"
              onClick={() => pick(c)}
              className="flex w-full flex-col items-start px-3 py-2 text-left text-sm transition hover:opacity-80"
              style={{ color: "var(--text)" }}
              onMouseEnter={(e) =>
                (e.currentTarget.style.background = "var(--bg-hover)")
              }
              onMouseLeave={(e) =>
                (e.currentTarget.style.background = "transparent")
              }
            >
              <span className="font-medium">{c.name}</span>
              {c.name !== c.email && (
                <span
                  className="text-xs"
                  style={{ color: "var(--text-faint)" }}
                >
                  {c.email}
                </span>
              )}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

function quickScheduleOptions(): { label: string; at: () => Date }[] {
  return [
    { label: "In 1 hour", at: () => new Date(Date.now() + 60 * 60 * 1000) },
    {
      label: "This evening",
      at: () => {
        const d = new Date();
        d.setHours(18, 0, 0, 0);
        if (d.getTime() <= Date.now()) d.setDate(d.getDate() + 1);
        return d;
      },
    },
    {
      label: "Tomorrow morning",
      at: () => {
        const d = new Date();
        d.setDate(d.getDate() + 1);
        d.setHours(8, 0, 0, 0);
        return d;
      },
    },
  ];
}

export function ComposeModal({
  initialDraft,
  onClose,
  onSaveDraft,
  onSend,
  onScheduleSend,
  onDeleteDraft,
  onValidationError,
  onEditSignature,
  primaryEmail,
  aliases,
  contacts,
}: ComposeModalProps) {
  const [draft, setDraft] = useState<ComposeDraft>({
    from: primaryEmail,
    attachments: [],
    ...initialDraft,
  });
  const [minimized, setMinimized] = useState(false);
  const [full, setFull] = useState(() => getComposeStyle() === "full");
  const isMobile = useIsMobile();
  const effectiveFull = full || isMobile;
  const [showCc, setShowCc] = useState(
    Boolean(initialDraft.cc || initialDraft.bcc),
  );
  const [quoteExpanded, setQuoteExpanded] = useState(false);
  const [sending, setSending] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [scheduleOpen, setScheduleOpen] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const bodyRef = useRef<HTMLDivElement>(null);
  const scheduleRef = useRef<HTMLDivElement>(null);

  function isEmpty(d: ComposeDraft) {
    return (
      !d.subject.trim() &&
      !d.body.trim() &&
      !d.quoteBody?.trim() &&
      (d.attachments?.length ?? 0) === 0
    );
  }

  function toggleFull() {
    const next = !full;
    setFull(next);
    setComposeStyle(next ? "full" : "popup");
  }

  function handleCloseWithSave() {
    const hasContent =
      draft.to.trim() ||
      draft.subject.trim() ||
      draft.body.trim() ||
      (draft.attachments?.length ?? 0) > 0;
    if (hasContent) onSaveDraft(draft);
    onClose();
  }

  useEffect(() => {
    setDraft({ from: primaryEmail, attachments: [], ...initialDraft });
    setShowCc(Boolean(initialDraft.cc || initialDraft.bcc));
    setQuoteExpanded(false);
    // contentEditable is intentionally uncontrolled (see handleBodyInput) --
    // only pushed into the DOM imperatively here, on initial mount or when
    // swapping to a different draft (e.g. opening a different saved draft),
    // never on every keystroke re-render.
    if (bodyRef.current) {
      bodyRef.current.innerHTML = initialDraft.html || "";
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialDraft]);

  useEffect(() => {
    if (!scheduleOpen) return;
    function handleClick(e: MouseEvent) {
      if (
        scheduleRef.current &&
        !scheduleRef.current.contains(e.target as Node)
      )
        setScheduleOpen(false);
    }
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, [scheduleOpen]);

  function handleBodyInput() {
    const el = bodyRef.current;
    if (!el) return;
    setDraft((d) => ({ ...d, body: el.innerText, html: el.innerHTML }));
  }

  function runCommand(command: string, arg?: string) {
    bodyRef.current?.focus();
    document.execCommand(command, false, arg);
    handleBodyInput();
  }

  function insertLink() {
    const url = window.prompt("Link URL");
    if (url) runCommand("createLink", url);
  }

  function addFiles(files: FileList | null) {
    if (!files) return;
    // Snapshot into a real array synchronously, here -- the file input's
    // onChange clears the input (e.target.value = '') right after this
    // returns, which also empties the live FileList e.target.files still
    // references. Array.from(files) deferred into the setState updater
    // (React doesn't always run updater functions synchronously) would
    // iterate that already-emptied FileList and silently drop every file.
    const picked = Array.from(files);
    setDraft((d) => ({
      ...d,
      attachments: [...(d.attachments || []), ...picked],
    }));
  }

  function removeFile(index: number) {
    setDraft((d) => ({
      ...d,
      attachments: (d.attachments || []).filter((_, i) => i !== index),
    }));
  }

  function validate(): boolean {
    if (!draft.to.trim()) {
      onValidationError("Add at least one recipient before sending");
      return false;
    }
    if (isEmpty(draft)) {
      onValidationError(
        "Cannot send an empty message -- add a subject, body, or attachment",
      );
      return false;
    }
    return true;
  }

  async function handleSend() {
    if (!validate()) return;
    setSending(true);
    try {
      await onSend(draft);
    } finally {
      setSending(false);
    }
  }

  async function handleSchedule(sendAt: Date) {
    if (!validate()) return;
    setScheduleOpen(false);
    setSending(true);
    try {
      await onScheduleSend(draft, sendAt);
    } finally {
      setSending(false);
    }
  }

  async function handleDelete() {
    if (!onDeleteDraft) return;
    setDeleting(true);
    try {
      await onDeleteDraft(draft);
    } finally {
      setDeleting(false);
    }
  }

  if (minimized) {
    return (
      <div
        className="fixed bottom-0 right-3 z-50 w-72 max-w-[calc(100vw-1.5rem)] cursor-pointer rounded-t-xl border border-b-0 px-4 py-3 shadow-lg sm:right-6"
        style={{
          background: "var(--bg-elevated)",
          borderColor: "var(--border)",
        }}
        onClick={() => setMinimized(false)}
      >
        <div className="flex items-center justify-between">
          <span
            className="truncate text-sm font-medium"
            style={{ color: "var(--text)" }}
          >
            {draft.subject || "New message"}
          </span>
          <button
            onClick={(e) => {
              e.stopPropagation();
              handleCloseWithSave();
            }}
            style={{ color: "var(--text-faint)" }}
          >
            <X size={16} />
          </button>
        </div>
      </div>
    );
  }

  return (
    <div
      className={
        effectiveFull
          ? "fixed inset-0 z-50 flex flex-col overflow-hidden border-0 shadow-2xl sm:inset-4 sm:rounded-xl sm:border md:inset-10"
          : "fixed bottom-0 inset-x-3 z-50 flex flex-col overflow-hidden rounded-t-xl border border-b-0 shadow-2xl sm:inset-x-auto sm:right-6 sm:w-[440px]"
      }
      style={{
        background: "var(--bg-elevated)",
        borderColor: "var(--border)",
        maxHeight: effectiveFull ? undefined : "min(32rem, 85vh)",
      }}
    >
      <div
        className="flex items-center justify-between px-4 py-2.5"
        style={{ background: "var(--accent)" }}
      >
        <span className="text-sm font-medium text-white">New message</span>
        <div className="flex items-center gap-1">
          <button
            onClick={() => setMinimized(true)}
            className="rounded p-1 text-white/90 hover:bg-white/10"
          >
            <Minus size={15} />
          </button>
          {!isMobile && (
            <button
              onClick={toggleFull}
              className="rounded p-1 text-white/90 hover:bg-white/10"
              title={full ? "Restore" : "Maximize"}
            >
              {full ? <Minimize2 size={14} /> : <Maximize2 size={14} />}
            </button>
          )}
          <button
            onClick={handleCloseWithSave}
            className="rounded p-1 text-white/90 hover:bg-white/10"
          >
            <X size={16} />
          </button>
        </div>
      </div>

      {/* Scrolls independently of the header/footer so the Send button
          below stays reachable even when the on-screen keyboard (mobile)
          or a long quote/attachment list eats most of the modal's height. */}
      <div className="flex min-h-0 flex-1 flex-col overflow-y-auto">
        <div
          className="flex flex-col gap-0 border-b"
          style={{ borderColor: "var(--border)" }}
        >
          {aliases.length > 0 && (
            <div
              className="relative border-b"
              style={{ borderColor: "var(--border)" }}
            >
              <select
                value={draft.from}
                onChange={(e) => setDraft({ ...draft, from: e.target.value })}
                className="w-full appearance-none px-4 py-2.5 text-base outline-none sm:text-sm"
                style={{ color: "var(--text)", background: "transparent" }}
              >
                <option value={primaryEmail}>From: {primaryEmail}</option>
                {aliases.map((alias) => (
                  <option key={alias} value={alias}>
                    From: {alias}
                  </option>
                ))}
              </select>
              <ChevronDown
                size={14}
                className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2"
                style={{ color: "var(--text-faint)" }}
              />
            </div>
          )}
          <div
            className="flex items-center border-b"
            style={{ borderColor: "var(--border)" }}
          >
            <RecipientField
              value={draft.to}
              onChange={(v) => setDraft({ ...draft, to: v })}
              placeholder="To"
              contacts={contacts}
            />
            {!showCc && (
              <button
                onClick={() => setShowCc(true)}
                className="px-3 py-2.5 text-xs font-medium"
                style={{ color: "var(--text-faint)" }}
              >
                Cc/Bcc
              </button>
            )}
          </div>
          {showCc && (
            <>
              <RecipientField
                value={draft.cc || ""}
                onChange={(v) => setDraft({ ...draft, cc: v })}
                placeholder="Cc"
                contacts={contacts}
                borderBottom
              />
              <RecipientField
                value={draft.bcc || ""}
                onChange={(v) => setDraft({ ...draft, bcc: v })}
                placeholder="Bcc"
                contacts={contacts}
                borderBottom
              />
            </>
          )}
          <input
            value={draft.subject}
            onChange={(e) => setDraft({ ...draft, subject: e.target.value })}
            placeholder="Subject"
            className="px-4 py-2.5 text-base outline-none sm:text-sm"
            style={{ color: "var(--text)", background: "transparent" }}
          />
        </div>

        <div
          className="flex items-center gap-0.5 border-b px-2 py-1"
          style={{ borderColor: "var(--border)" }}
        >
          <ToolbarButton
            icon={Bold}
            title="Bold"
            onRun={() => runCommand("bold")}
          />
          <ToolbarButton
            icon={Italic}
            title="Italic"
            onRun={() => runCommand("italic")}
          />
          <ToolbarButton
            icon={Underline}
            title="Underline"
            onRun={() => runCommand("underline")}
          />
          <ToolbarButton
            icon={List}
            title="Bulleted list"
            onRun={() => runCommand("insertUnorderedList")}
          />
          <ToolbarButton
            icon={ListOrdered}
            title="Numbered list"
            onRun={() => runCommand("insertOrderedList")}
          />
          <ToolbarButton icon={Link2} title="Link" onRun={insertLink} />
        </div>

        <div
          ref={bodyRef}
          contentEditable
          onInput={handleBodyInput}
          data-placeholder="Write your message..."
          className="compose-body flex-1 px-4 py-3 text-base outline-none sm:text-sm"
          style={{
            color: "var(--text)",
            background: "transparent",
            minHeight: "140px",
          }}
        />

        {(draft.quoteBody || draft.quoteHeading) && (
          <div
            className="shrink-0 border-t"
            style={{ borderColor: "var(--border)" }}
          >
            <button
              onClick={() => setQuoteExpanded((v) => !v)}
              className="flex w-full items-center gap-1.5 px-4 py-2 text-xs font-medium"
              style={{ color: "var(--text-faint)" }}
            >
              {quoteExpanded ? (
                <ChevronDown size={14} />
              ) : (
                <ChevronRight size={14} />
              )}
              <span>
                {quoteExpanded ? "Hide quoted text" : "Show quoted text"}
              </span>
            </button>
            {quoteExpanded && (
              <div
                className="mx-4 mb-3 max-h-48 overflow-y-auto rounded-lg border-l-4 px-3 py-2 text-xs leading-relaxed"
                style={{
                  borderColor: "var(--border)",
                  background: "var(--bg)",
                  color: "var(--text-faint)",
                }}
              >
                {draft.quoteHeading && (
                  <p
                    className="mb-1.5 whitespace-pre-wrap font-medium"
                    style={{ color: "var(--text-muted)" }}
                  >
                    {draft.quoteHeading}
                  </p>
                )}
                {draft.quoteBody && (
                  <pre className="whitespace-pre-wrap font-sans">
                    {draft.quoteBody}
                  </pre>
                )}
              </div>
            )}
          </div>
        )}

        {(draft.attachments?.length || 0) > 0 && (
          <div
            className="flex flex-wrap gap-2 border-t px-4 py-3"
            style={{ borderColor: "var(--border)" }}
          >
            {draft.attachments!.map((file, i) => (
              <div
                key={`${file.name}-${i}`}
                className="flex items-center gap-1.5 rounded-lg border px-2.5 py-1.5 text-xs"
                style={{
                  borderColor: "var(--border)",
                  color: "var(--text-muted)",
                }}
              >
                <FileIcon size={13} />
                <span className="max-w-[140px] truncate">{file.name}</span>
                <span style={{ color: "var(--text-faint)" }}>
                  {formatSize(file.size)}
                </span>
                <button
                  onClick={() => removeFile(i)}
                  style={{ color: "var(--text-faint)" }}
                >
                  <X size={12} />
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

      <div
        className="flex items-center justify-between border-t px-4 py-3"
        style={{ borderColor: "var(--border)" }}
      >
        <div className="flex items-center">
          <button
            onClick={handleSend}
            disabled={sending}
            className="flex items-center gap-2 rounded-l-lg px-4 py-2 text-sm font-medium text-white transition hover:opacity-90 disabled:opacity-60"
            style={{ background: "var(--accent)" }}
          >
            {sending ? "Sending…" : "Send"}
            <Send size={14} />
          </button>
          <div className="relative" ref={scheduleRef}>
            <button
              onClick={() => setScheduleOpen((v) => !v)}
              disabled={sending}
              title="Schedule send"
              className="flex items-center rounded-r-lg py-2.5 pl-1.5 pr-2 text-white transition hover:opacity-90 disabled:opacity-60"
              style={{
                background: "var(--accent)",
                borderLeft: "1px solid rgba(255,255,255,0.35)",
              }}
            >
              <ChevronDown size={14} />
            </button>
            {scheduleOpen && (
              <div
                className="absolute bottom-full left-0 z-10 mb-2 w-56 rounded-xl border py-1 shadow-lg"
                style={{
                  background: "var(--bg-elevated)",
                  borderColor: "var(--border)",
                }}
              >
                {quickScheduleOptions().map((opt) => (
                  <button
                    key={opt.label}
                    onClick={() => handleSchedule(opt.at())}
                    className="block w-full px-3 py-2 text-left text-sm transition hover:opacity-80"
                    style={{ color: "var(--text)" }}
                    onMouseEnter={(e) =>
                      (e.currentTarget.style.background = "var(--bg-hover)")
                    }
                    onMouseLeave={(e) =>
                      (e.currentTarget.style.background = "transparent")
                    }
                  >
                    {opt.label}
                  </button>
                ))}
                <div
                  className="border-t px-3 py-2"
                  style={{ borderColor: "var(--border)" }}
                >
                  <label
                    className="mb-1 block text-xs"
                    style={{ color: "var(--text-faint)" }}
                  >
                    Custom date &amp; time
                  </label>
                  <input
                    type="datetime-local"
                    min={new Date(Date.now() + 60000)
                      .toISOString()
                      .slice(0, 16)}
                    onChange={(e) => {
                      if (e.target.value)
                        handleSchedule(new Date(e.target.value));
                    }}
                    className="w-full rounded border px-2 py-1 text-sm outline-none"
                    style={{
                      borderColor: "var(--border)",
                      color: "var(--text)",
                      background: "transparent",
                    }}
                  />
                </div>
              </div>
            )}
          </div>
        </div>
        <div className="flex items-center gap-1">
          <input
            ref={fileInputRef}
            type="file"
            multiple
            className="hidden"
            onChange={(e) => {
              addFiles(e.target.files);
              e.target.value = "";
            }}
          />
          <button
            onClick={() => fileInputRef.current?.click()}
            style={{ color: "var(--text-faint)" }}
            className="rounded-lg p-2 hover:opacity-80"
            title="Attach files"
          >
            <Paperclip size={17} />
          </button>
          <button
            onClick={onEditSignature}
            style={{ color: "var(--text-faint)" }}
            className="rounded-lg p-2 hover:opacity-80"
            title="Edit signature"
          >
            <PenLine size={17} />
          </button>
          {onDeleteDraft && draft.draftUid != null && (
            <button
              onClick={handleDelete}
              disabled={deleting}
              style={{ color: "var(--danger)" }}
              className="rounded-lg p-2 hover:opacity-80 disabled:opacity-60"
              title="Delete draft"
            >
              <Trash2 size={17} />
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
